"""Experimental V2 protocol layer for the FMA trusted kernel.

This package is additive: it does not alter legacy hashes, replay behavior, or
promotion semantics in :mod:`fma`.  V2 objects are content-addressed proposals
and bindings that can be projected into the existing bounded-ILP kernel.
"""

from .bridge import AcceptanceTestAuthority, freeze_legacy_contract
from .codex_discovery import CodexProblemDiscoveryExplorer
from .discovery import (
    ProblemDiscoveryContext,
    ProblemDiscoveryExplorer,
    ProblemDiscoveryHarness,
    ProblemDiscoveryProposal,
    ProblemHypothesisDraft,
)
from .discovery_store import DiscoveryRunState, DiscoveryRunStore, ProblemAdmissionOutcome
from .intake import ingest_local_brief
from .capacity_decision import CapacityDecisionEvaluator
from .empirical_capacity import (
    EmpiricalCapacityOutcome,
    run_empirical_capacity_fixture,
    verify_empirical_run,
)
from .empirical_schemas import (
    CapacityDecisionSpec,
    DecisionStabilityReport,
    EmpiricalRunManifest,
    ForecastCandidatePortfolio,
    ForecastCandidateSpec,
    ForecastCandidateSpecV22,
    ForecastValidationReport,
    TemporalValidationSpec,
    TimeSeriesDataContract,
    TimeSeriesPoint,
    TimeSeriesSnapshot,
)
from .forecast_evaluator import RollingOriginForecastEvaluator
from .forecast_generators import (
    generate_default_forecast_portfolio,
    generate_failure_evolved_forecast_portfolio,
)
from .dynamics_knowledge import (
    DynamicsKnowledgeBundleV24,
    DynamicsKnowledgeOutcome,
    capture_dynamics_knowledge,
    verify_dynamics_knowledge_run,
)
from .dynamics_ir import (
    DynamicsArmPolicyV24,
    DynamicsDataSnapshotV24,
    DynamicsFitResultV24,
    DynamicsModelIRV24,
    DynamicsSelectionReceiptV24,
    default_dynamics_arm_policy,
    fit_dynamics_candidate,
    guarded_dynamics_arm_policy_v24,
    safe_dynamics_arm_policy_v24,
    select_dynamics_candidate,
)
from .dynamics_integral import (
    DynamicsCandidateDefinitionV25,
    DynamicsEstimatorPolicyV25,
    DynamicsFitResultV25,
    DynamicsModelIRV25,
    DynamicsSelectionReceiptV25,
    assert_single_component_estimator_ablation_v25,
    default_estimator_policy_v25,
    fit_dynamics_candidate_v25,
    select_dynamics_candidate_v25,
)
from .dynamics_estimator_ablation import (
    DynamicsEstimatorAblationReportV25,
    DynamicsEstimatorExperimentSpecV25,
    DynamicsEstimatorOutcomeV25,
    DynamicsEstimatorQualificationV25,
    default_estimator_confirmation_spec_v25,
    default_estimator_exploratory_spec_v25,
    failure_evolved_estimator_exploratory_spec_v25,
    run_estimator_worldpack_v25,
    verify_estimator_worldpack_run_v25,
)
from .dynamics_stability import (
    DynamicsStabilityProtocolV25,
    DynamicsStabilityReportV25,
    default_stability_protocol_v25,
    evaluate_dynamics_stability_v25,
)
from .dynamics_active_design import (
    ActiveDesignPolicyV26,
    ActiveDesignReportV26,
    ActiveDesignWorldPackSpecV26,
    default_active_design_confirmation_spec_v26,
    default_active_design_exploratory_spec_v26,
    default_active_design_policies_v26,
    failure_evolved_active_design_exploratory_spec_v26,
    run_active_design_worldpack_v26,
    verify_active_design_worldpack_run_v26,
)
from .dynamics_active_design_effect import (
    ActiveDesignEffectProtocolV261,
    ActiveDesignEffectQualificationV261,
    ActiveDesignEffectReportV261,
    default_confirmation_effect_protocol_v261,
    default_exploratory_effect_protocol_v261,
    run_active_design_effect_worldpack_v261,
    verify_active_design_effect_run_v261,
)
from .dynamics_worldpack import (
    DynamicsOperatorQualificationV24,
    DynamicsWorldPackOutcome,
    DynamicsWorldPackReportV24,
    DynamicsWorldPackSpecV24,
    default_confirmation_dynamics_spec_v24,
    default_exploratory_dynamics_spec_v24,
    guarded_confirmation_dynamics_spec_v24,
    run_dynamics_worldpack,
    verify_dynamics_worldpack_run,
)
from .timeseries_intake import ingest_local_timeseries_csv
from .official_data import (
    OfficialDataReceipt,
    fetch_bls_monthly_series,
    fetch_usgs_daily_values,
)
from .official_shadow import (
    OfficialShadowOutcome,
    OfficialShadowReport,
    run_official_shadow_benchmark,
    verify_official_shadow_run,
)
from .shift_diagnostics import WindowShiftEvaluator, WindowShiftReport, WindowShiftSpec
from .statistical_evaluator import (
    ForecastSkillUncertaintyEvaluator,
    ForecastSkillUncertaintyReport,
    MovingBlockBootstrapSpec,
)
from .schemas import (
    AcceptanceCommitment,
    ApprovalRecord,
    ConceptualModelIR,
    DiscoveryArtifactRef,
    DiscoveryEvent,
    DiscoveryProviderObservation,
    DiscoveryRejectionReceipt,
    EvidencePedigree,
    EvidenceSnapshot,
    EvidenceUseEvent,
    EvidenceUseReservation,
    FrozenLegacyBinding,
    MissionContract,
    MissionSpec,
    PrivateAcceptanceBundle,
    ProblemContractProposal,
    ProblemHypothesis,
    TransactionEvent,
    TransactionProposal,
)

__all__ = [
    "AcceptanceCommitment",
    "AcceptanceTestAuthority",
    "ActiveDesignEffectProtocolV261",
    "ActiveDesignEffectQualificationV261",
    "ActiveDesignEffectReportV261",
    "ActiveDesignPolicyV26",
    "ActiveDesignReportV26",
    "ActiveDesignWorldPackSpecV26",
    "ApprovalRecord",
    "CapacityDecisionEvaluator",
    "CapacityDecisionSpec",
    "ConceptualModelIR",
    "CodexProblemDiscoveryExplorer",
    "DiscoveryArtifactRef",
    "DiscoveryEvent",
    "DiscoveryProviderObservation",
    "DiscoveryRejectionReceipt",
    "DiscoveryRunState",
    "DiscoveryRunStore",
    "DynamicsArmPolicyV24",
    "DynamicsCandidateDefinitionV25",
    "DynamicsDataSnapshotV24",
    "DynamicsEstimatorAblationReportV25",
    "DynamicsEstimatorExperimentSpecV25",
    "DynamicsEstimatorOutcomeV25",
    "DynamicsEstimatorPolicyV25",
    "DynamicsEstimatorQualificationV25",
    "DynamicsFitResultV24",
    "DynamicsFitResultV25",
    "DynamicsKnowledgeBundleV24",
    "DynamicsKnowledgeOutcome",
    "DynamicsModelIRV24",
    "DynamicsModelIRV25",
    "DynamicsOperatorQualificationV24",
    "DynamicsSelectionReceiptV24",
    "DynamicsSelectionReceiptV25",
    "DynamicsStabilityProtocolV25",
    "DynamicsStabilityReportV25",
    "DynamicsWorldPackOutcome",
    "DynamicsWorldPackReportV24",
    "DynamicsWorldPackSpecV24",
    "DecisionStabilityReport",
    "EmpiricalCapacityOutcome",
    "EmpiricalRunManifest",
    "EvidencePedigree",
    "EvidenceSnapshot",
    "EvidenceUseEvent",
    "EvidenceUseReservation",
    "FrozenLegacyBinding",
    "ForecastCandidatePortfolio",
    "ForecastCandidateSpec",
    "ForecastCandidateSpecV22",
    "ForecastValidationReport",
    "ForecastSkillUncertaintyEvaluator",
    "ForecastSkillUncertaintyReport",
    "MissionContract",
    "MissionSpec",
    "MovingBlockBootstrapSpec",
    "OfficialDataReceipt",
    "OfficialShadowOutcome",
    "OfficialShadowReport",
    "PrivateAcceptanceBundle",
    "ProblemContractProposal",
    "ProblemDiscoveryContext",
    "ProblemDiscoveryExplorer",
    "ProblemDiscoveryHarness",
    "ProblemDiscoveryProposal",
    "ProblemAdmissionOutcome",
    "ProblemHypothesis",
    "ProblemHypothesisDraft",
    "RollingOriginForecastEvaluator",
    "TemporalValidationSpec",
    "TimeSeriesDataContract",
    "TimeSeriesPoint",
    "TimeSeriesSnapshot",
    "WindowShiftEvaluator",
    "WindowShiftReport",
    "WindowShiftSpec",
    "TransactionEvent",
    "TransactionProposal",
    "freeze_legacy_contract",
    "generate_default_forecast_portfolio",
    "generate_failure_evolved_forecast_portfolio",
    "fetch_bls_monthly_series",
    "fetch_usgs_daily_values",
    "capture_dynamics_knowledge",
    "assert_single_component_estimator_ablation_v25",
    "default_active_design_confirmation_spec_v26",
    "default_active_design_exploratory_spec_v26",
    "default_active_design_policies_v26",
    "default_confirmation_effect_protocol_v261",
    "default_confirmation_dynamics_spec_v24",
    "default_dynamics_arm_policy",
    "default_exploratory_dynamics_spec_v24",
    "default_estimator_confirmation_spec_v25",
    "default_estimator_exploratory_spec_v25",
    "default_exploratory_effect_protocol_v261",
    "failure_evolved_active_design_exploratory_spec_v26",
    "failure_evolved_estimator_exploratory_spec_v25",
    "default_estimator_policy_v25",
    "default_stability_protocol_v25",
    "evaluate_dynamics_stability_v25",
    "fit_dynamics_candidate",
    "fit_dynamics_candidate_v25",
    "guarded_confirmation_dynamics_spec_v24",
    "guarded_dynamics_arm_policy_v24",
    "ingest_local_brief",
    "ingest_local_timeseries_csv",
    "run_empirical_capacity_fixture",
    "run_dynamics_worldpack",
    "run_active_design_effect_worldpack_v261",
    "run_active_design_worldpack_v26",
    "run_estimator_worldpack_v25",
    "run_official_shadow_benchmark",
    "safe_dynamics_arm_policy_v24",
    "select_dynamics_candidate",
    "select_dynamics_candidate_v25",
    "verify_dynamics_knowledge_run",
    "verify_dynamics_worldpack_run",
    "verify_active_design_effect_run_v261",
    "verify_active_design_worldpack_run_v26",
    "verify_estimator_worldpack_run_v25",
    "verify_empirical_run",
    "verify_official_shadow_run",
]
